### ISSUE TITLE
error: "version" is a required argument.

### ISSUE THREAD

**Issue by justintidev** [BlessCSS/bless-brunch#6]
Hello,
I have a probleme when i used "brunch build" in production mode.
Console give the following message : 

```
info: Using outdated versions of bless-brunch, trying to update to match package.json versions
info: compiling
error: "version" is a required argument.
```

I used brunch in version 2.10.9.

Can you help me fix this bug please ?

**Comment by thomasconner** [comment]
I will need to take a look at it as it  has been a while since I updated the plugin.

**Comment by justintidev** [comment]
Hello,
Thank you for your reply.
I still have the bug. Have you a fix for that ?

**Comment by thomasconner** [comment]
Not yet but I am working on it. Trying to update to the latest version of bless and brunch.

**Comment by thomasconner** [comment]
@justintidev I just updated the plugin. Please give it a try and see if it resolves your issue.

**Comment by ghost** [comment]
Hello,
Sorry for my late response. The problem persists.
To move forward, I removed Bless from my project and I cut my CSS myself :/
